security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_memory:
            memory:
                users:
                    jaytaph: { password: '$2y$13$T9iC44oygjqlLI4jEOXdJ.OD2S186Ewlny3I6vq0eXYg3srYmUsY2', roles: ['ROLE_USER'] }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            security: true
            context: api
            stateless: true
            provider: users_in_memory
            oauth2: true

        main:
            pattern: ^/
            security: true
            context: api
            lazy: true
            provider: users_in_memory
            form_login:
                check_path: app_login
                login_path: app_login

    access_control:
        - { path: ^/oauth/authorize, roles: IS_AUTHENTICATED_REMEMBERED }

        - { path: ^/api/v1/instance, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/apps, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/accounts/verify_credentials, roles: ROLE_OAUTH2_READ }
        - { path: ^/api, roles: ROLE_USER }


when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
