# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    image_path: '%kernel.project_dir%/public/media/images'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $captchaEnabled: '%env(bool:HCAPTCHA_ENABLED)%'

    _instanceof:
        App\Service\Inbox\TypeProcessorInterface:
            tags: ['app.inbox.type_processor']
        App\Service\Queue\WorkerInterface:
            tags: ['app.queue.worker']

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Security\OAuth\DevelopmentAuthenticator:
        arguments:
            $oauthOverride: '%env(bool:OAUTH_OVERRIDE)%'
            $oauthOverrideUser: '%env(string:OAUTH_OVERRIDE_USER)%'

    App\Service\MediaService:
        arguments:
            $imagePath: '%image_path%'

    App\Service\InboxService:
        arguments:
            - !tagged_iterator { tag: 'app.inbox.type_processor' }

    App\Service\Queue\Queue:
        arguments:
            - !tagged_iterator { tag: 'app.queue.worker' }
